name: GitHub Organization repo list
description:  Used to extract the repo list at org level
author: ManiKandan

inputs:
  token:
    description: GitHub Access Token.
    required: true
  outputDir:
      description: The output directory for the report.
      required: true
      default: ${{ github.workspace }}
  organization:
    description: The organization name.
    required: true
runs:
  using: node12
  main: dist/index.js